FROM debian:buster-slim

ENV GDAL_VERSION=%%GDAL_VERSION%%

RUN \
      apt-get update \
      && apt-get install -y --no-install-recommends \
         gdal-bin=${GDAL_VERSION}+* \
         python-gdal=${GDAL_VERSION}+*
